version: '3.8'

services:
  thermostat-service:
    image: thermostat-service:latest
    build:
      context: .
      dockerfile: Server/Dockerfile
    ports:
      - "8081:8081"
      - "9090:9090"
    environment:
      - SERVER_PORT=8081
      - GRPC_SERVER_PORT=9090

  custom-client:
    image: custom-client:latest
    build:
      context: .
      dockerfile: CustomClient/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - GRPC_SERVER_ADDRESS=thermostat-service:9090
    depends_on:
      - thermostat-service
